In [1]:
import pandas as pd
import numpy as np

In [7]:
data= pd.read_csv(r"C:\Users\vidhi\Documents\GitHub\FPD_Analysis\data.csv", sep=',', header=None)

In [21]:
data

0    1    2    3    4     5           6
0    0   77  250  186  140  2250  356.299597
1    1  120  350  337  250  2050  594.711794
2    2   50  250  120  180  2750  397.169697
3    3   77  450  242  280  2100  533.652731
4    4   50  200  109  200  3450  475.882888
..  ..  ...  ...  ...  ...   ...         ...
76  76  120  400  357  250  3250  790.500668
77  77   50  400  149  240  1650  363.484711
78  78   50  250  120  170  2600  369.149884
79  79  120  350  337  270  2200  623.609487
80  80   50  450  157  160  2250  375.888338

[81 rows x 7 columns]

In [9]:
x= data.iloc[:,0:6].to_numpy()
y= data.iloc[:,6].to_numpy()

In [22]:
print(x)

[[   0   77  250  186  140 2250]
 [   1  120  350  337  250 2050]
 [   2   50  250  120  180 2750]
 [   3   77  450  242  280 2100]
 [   4   50  200  109  200 3450]
 [   5   50  400  149  250 2050]
 [   6  120  300  314  210 3400]
 [   7  100  450  314  150 2550]
 [   8  120  300  314  250 2500]
 [   9  120  350  337  260 3350]
 [  10  100  300  261  170 3000]
 [  11  100  300  261  220 3500]
 [  12   50  450  157  290 2800]
 [  13   77  300  202  180 3150]
 [  14  120  250  289  170 1500]
 [  15  100  250  241  200 2450]
 [  16  120  250  289  150 2000]
 [  17   50  250  120  150 3200]
 [  18  120  350  337  190 1500]
 [  19  120  350  337  210 1650]
 [  20   50  300  131  170 3400]
 [  21   50  300  131  250 2550]
 [  22  120  350  337  210 1850]
 [  23   77  400  230  200 2900]
 [  24  120  350  337  190 3300]
 [  25  120  450  377  230 2900]
 [  26   50  200  109  230 2400]
 [  27   77  400  230  250 2200]
 [  28  100  250  241  290 2000]
 [  29   50  400  149  270 2350]
 [  30  10

In [10]:
print(y)

[356.2995965 594.7117945 397.1696973 533.6527312 475.8828877 419.4245187
 711.2898343 541.5388347 630.480341  784.7885018 558.0701835 682.4359277
 545.3691994 530.4304522 420.9039418 512.9576885 446.7888892 382.6971598
 488.5032947 519.0499552 456.6873923 455.6030014 545.432786  568.4774227
 702.5111452 745.7881396 394.7736027 519.5370003 504.7810886 466.8447227
 797.4837935 541.7115156 404.4629393 642.5091799 501.3825274 629.9229934
 500.8773496 575.0567456 493.7101956 421.5740609 570.9365464 311.9324739
 440.2372941 590.8114438 553.1311155 426.002911  440.9649635 520.2895964
 608.797323  480.0529465 416.0375934 277.7627831 660.7711645 373.8529064
 472.7268121 701.6041968 513.9064712 339.5149337 572.7937595 404.4629393
 570.3624506 585.0868557 480.8035371 716.5890236 383.8315579 657.7644084
 788.0552638 388.013101  399.825208  498.5188482 561.1110392 425.6116148
 414.3361357 524.132353  330.3410744 487.9805454 790.5006682 363.4847111
 369.1498845 623.609487  375.8883379]


In [11]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size = 0.7, 
                                                    test_size = 0.3, random_state = 42)

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr = LinearRegression().fit(X_train, y_train)

In [26]:
print("lr.coef_: {}".format(lr.coef_))
print("lr.intercept_: {}".format(lr.intercept_))


lr.coef_: [0.07098331 0.70425384 0.13203804 0.74948268 0.89781809 0.1231039 ]
lr.intercept_: -263.366042614738


In [27]:
print("Training set score: {:.2f}".format(lr.score(X_train, y_train)))
print("Test set score: {:.2f}".format(lr.score(X_test, y_test)))

Training set score: 0.99
Test set score: 0.99
